### ISSUE TITLE
Segment error (core dumped)

### ISSUE THREAD

**Issue by CZ-CHO** [drormoran/Equivariant-SFM#2]
Hello author. It's a good job! However, when I use your data for training, I always have an error "Segment error (core dumped)" after training for a period of time, and then the training ends. I have checked this error on the Internet. It may be due to memory out of bounds or pointer memory access error etc. I suspect that it is most likely that an error occurred when using cere for BA, but I am not very familiar with your code, and it will be difficult to locate the error for me. I'm wondering if you have encountered this problem. Do you have any good suggestions?
Due to the computer configuration (The GPU is only a 3080ti and the GPU memory is 12G, and the number of CPU threads is 16), when I was training, I set the batch_size to 2, and then changed the number of threads during cere optimization to 16.

**Comment by drormoran** [comment]
Hi,

We haven't encounter this problem yet.
Are you sure it is because of the ceres BA? Can You turn off the BA and see if it still occurs? You have this option in the config file under ba.run_ba

**Comment by CZ-CHO** [comment]
Thank you for your reply and suggestion! 
I tried to turn off the BA but it still reported the error. In addition, I tried to set the batch_size to 1, but it still didn't work. I wonder if it's because the GPU is out of memory.  I still have the following two questions and look forward to your reply: 
1. Can you tell me how much GPU memory you need when the batch size is 4?
2. I found that the GPU memory occupation is always changing during training. So I want to ask a maybe naive question. Is this model related to the size of the input data? Will the larger the data, the more GPU memory will be required？

**Comment by drormoran** [comment]
Usually, when there is not enough GPU memory you will get an "cuda out of memory" error and not a segment error.

The model size is constant so the required amount of memory depends mainly on your input size. For single scene optimization, 12GB of GPU memory is enough for most of the scenes. 

Can you send us an example of the error you get?

**Comment by CZ-CHO** [comment]
The error in the screenshot is in Chinese. Translated as "segment error (core dumped)".
I only modified the num_threads to 16 in line 173 and 242 of the ceres_utils.py, and using the command ‘python multiple_scenes_learning.py --conf Learning_Euc.conf --external_params "dataset:batch_size:2"‘

![2021-12-19 18-50-39屏幕截图](https://user-images.githubusercontent.com/46711404/146672364-c2936f70-3319-4737-8bff-1425d1f734e7.png)

**Comment by drormoran** [comment]
It seems like you have a single scene in your training set, did you change the conf file?

**Comment by CZ-CHO** [comment]
No, I do not change anything of Learning_Euc.conf.

**Comment by CZ-CHO** [comment]
This error also  occurred when I used my data to optimization. It is generated after obtaining the final output result. That means I've got 'final_ plots.html' file. The results look great. With the errors here, I don't know whether you can see what's wrong with Segment error.
![2021-12-22 21-58-32屏幕截图](https://user-images.githubusercontent.com/46711404/147105485-a98f22f1-eb0d-41f0-9908-89f5008af97c.png)

**Comment by drormoran** [comment]
Are you sure you didn't change the code or the conf file?

Your output is weird, it should be something lie this:
![image](https://user-images.githubusercontent.com/45562344/147159518-a89633cb-ba52-4343-8b21-d2b7e239eb91.png)

**Comment by CZ-CHO** [comment]
Yes, I also got this output at the beginning of training. The error occurred after training about 6 hours. I really do not change anything of the code, except the num_threads in ceres_utils.py, and the batch_size. 
![2021-12-24 10-01-58屏幕截图](https://user-images.githubusercontent.com/46711404/147306656-0727d05b-96f2-4e23-9bad-dfb715078950.png)
Under this setting, I trained again. Last night, the batch_size was set to 2. As a result, there was a problem of CUDA out of memory, and then there was a segment error under this error, as shown in the following figure. Now, I changed the batch_size to 1 and retrained it.
![2021-12-24 10-18-08屏幕截图](https://user-images.githubusercontent.com/46711404/147307693-1daf0c80-56a1-43ef-bdeb-262b96fc43eb.png)
Here I have another problem. When I use my own data for optimization, the reconstruction results I obtained look very good, but the depth is all negative. The results are centrosymmetry about the origin, as shown in the following figure:
![2021-12-24 10-41-54屏幕截图](https://user-images.githubusercontent.com/46711404/147309335-d1dc2f9a-dfe9-430b-a5d6-2f0fc70a9aca.png)
The M matrix I input is x=[2*i,j], y=[2*i+1,j], and then these coordinate points are the image coordinate points after undistortion. Although you said in your paper that the input is normalized coordinate points, I found that in the data you provided, the coordinate points also looked like pixel points (the coordinates were in the order of tens or hundreds), while the normalized coordinate point value is very small (about 1e-1). Moreover, when I input normalized coordinate points, the result is wrong.

**Comment by drormoran** [comment]
The data is M in pixels but than we normalized it in our code.
You can see it in code/datasets/SceneData.py, line 25:
        self.x = dataset_utils.M2sparse(M, normalize=True, Ns=Ns)

Does the depth negative also after BA?
Our hinge loss encourage positive depth, you can try to increase it weight by modifying the hinge_loss_weight paramter in the config file.

Regarding the segmentation faults I must admit that I really don't know what causing it. If you say its happens only after 6 hours you can try to reload the model you trained so far and resume your training (Don't forget to load the optimizer and the scheduler as well).

Anyway, sorry for the late response....

**Comment by CZ-CHO** [comment]
Thank you very much author. I found that the segment error is occurred every time, whether in training or optimization. And actually, this error will not have any impact on my training, because it only appears after the training is completed. I think this may be caused by some package versions of my computer, but anyway, just ignore it. Thank you again for your patience! 
        I recently encountered some difficulties while running your network:
1. Negative depth values also occurred during training, as shown in the following figure (using the default configuration of your code, in calibrated setting. Except that the batchsize is set to 1. Drinking Fountain Somewhere In Zurich, final result before BA)：
![df](https://user-images.githubusercontent.com/46711404/148063495-bc1d14d1-35bf-4429-8359-207b07413768.png)

2. I am wondering if it's convenient for you to tell me what configuration you use to get the best training results(in calibrated setting, including batch_size, lr, num_of_epochs, etc(anything different from your github code))? Because I can't get good results in training:
* the test final result(batch_size=1):
![图片](https://user-images.githubusercontent.com/46711404/148068641-3f7555b8-e245-4bbb-ace1-ba0bf5acf73b.png)

* the coordinate range is very large(Round Church Cambridge_ba, not reconstruct properly, which is the case in most scenes):
![图片](https://user-images.githubusercontent.com/46711404/148063853-14a366a7-4a7d-4b84-9b5e-38255d15a347.png)
![图片](https://user-images.githubusercontent.com/46711404/148064398-acff4888-c95a-4a9a-83d9-9159e5819836.png)

3. During training, the minimum loss always appears very early. When the epoch increases, the result becomes worse.
In the following figure: left: default configuration, except that epoch_size is 1, the best model is Ep12500; right: epoch_size=2 and epoches=100,000, the best model is Ep3500
![comp](https://user-images.githubusercontent.com/46711404/148066489-a37cfe5d-4849-4867-991d-96bb33780010.png)

        Looking forward to your reply!

**Comment by drormoran** [comment]
Hi,

If you say that the segment error is OK I'm closing this issue.
If you have some trouble training the model on your data, I think it will be better if we will talk by email. You can contact me at dror.moran at weizmann dot ac dot il.

 please contact me by my email
