### ISSUE TITLE
about results

### ISSUE THREAD

**Issue by ajunyo** [drormoran/Equivariant-SFM#4]
it's a nice job,but I found that the results were bad that the point cloud couldn't even produce a normal shape，Do I need to modify any super parameters。and，I did two experiments, using Locus point and not using Locus point，but it seems the same.thanks!
![5` (Q(NP4_8_V9%%N~@U59B](https://user-images.githubusercontent.com/96557468/154211849-543a0609-c44f-4e60-954a-09691d9be10f.png)
？

**Comment by drormoran** [comment]
Hi,

The current parameters should reproduce the results that appears on our paper.
Can you give me some more details on what you are trying to do? Is it a single scene reconstruction or a trained model?
Does this problem occurs on the reconstruction of this specific scene or for all your reconstruction?

What do you mean by using Locus point?

**Comment by ajunyo** [comment]
Thank you for your timely reply. Sorry to disturb you，

i use 

python multiple_scenes_learning.py --conf Learning_Proj.conf  to train this model,This is almost the result of all scenes。

 Locus point i mean use_gt=True

should i change some thing in conf? 

thank you!!!

 Original


From:"drormoran"< ***@***.*** &gt;;

Date:2022/2/16 15:40

To:"drormoran/Equivariant-SFM"< ***@***.*** &gt;;

CC:"我自己的邮箱"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [drormoran/Equivariant-SFM] about results (Issue #4)







Hi,

The current parameters should reproduce the results that appears on our paper.
Can you give me some more details on what you are trying to do? Is it a single scene reconstruction or a trained model?
Does this problem occurs on the reconstruction of this specific scene or for all your reconstruction?

What do you mean by using Locus point?

&amp;mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by drormoran** [comment]
There is an ambiguity in the uncalibrated setup reconstruction.
In this setup, you can apply any Homography on the scene and still have a good reconstruction. This is why your plot seems incorrect even when the reprojection error is low. This is why we usually don't look at those plot in the uncalibrated setup.

If you wish to reproduce the reconstruction shown in our paper you need to run your experiments on the calibrated setup, where this ambiguity doesn't exists.

**Comment by ajunyo** [comment]
Thank you very much for your timely reply. It's really an excellent job

**Comment by drormoran** [comment]
Thanks :)
